"""
synth/knowledge/history_geography.py — Hechos reales de historia y geografía.

Historia general (eventos reconocibles, figuras, períodos) y geografía
(países, capitales, continentes, características físicas). Todo
verificable en Wikipedia.
"""

from __future__ import annotations

from typing import List, Dict


_HISTORY_EVENTS = [
    ("French Revolution", "a political upheaval in France from 1789 to 1799",
     "un levantamiento político en Francia de 1789 a 1799",
     "Ended the monarchy, created the first French Republic, introduced the Declaration of the Rights of Man. Storming of the Bastille was July 14, 1789."),
    ("American Revolution", "the war where the thirteen colonies gained independence from Britain",
     "la guerra en la que las trece colonias ganaron su independencia de Gran Bretaña",
     "Lasted from 1775 to 1783. Declaration of Independence signed July 4, 1776. Led to the founding of the United States."),
    ("Industrial Revolution", "the transition to new manufacturing processes in Europe and the United States",
     "la transición a nuevos procesos de manufactura en Europa y Estados Unidos",
     "Began around 1760 in Britain. Steam engine, mechanized textile production, factories. Transformed economies and society."),
    ("World War I", "a global war from 1914 to 1918",
     "una guerra global de 1914 a 1918",
     "Triggered by the assassination of Archduke Franz Ferdinand. Allied Powers vs Central Powers. Ended with the Treaty of Versailles."),
    ("World War II", "a global war from 1939 to 1945",
     "una guerra global de 1939 a 1945",
     "Started with Germany's invasion of Poland. Allies vs Axis. Ended with Germany's surrender in May 1945 and Japan's in August."),
    ("Cold War", "the period of geopolitical tension between the US and Soviet Union",
     "el período de tensión geopolítica entre EEUU y la Unión Soviética",
     "From about 1947 to 1991. No direct military conflict. Featured the space race, nuclear arms race, and proxy wars."),
    ("fall of the Berlin Wall", "the event in 1989 that symbolized the end of the Cold War",
     "el evento de 1989 que simbolizó el fin de la Guerra Fría",
     "Happened on November 9, 1989. East Germans were allowed to cross into West Berlin. Led to German reunification in 1990."),
    ("Renaissance", "a cultural rebirth in Europe from the 14th to 17th centuries",
     "un renacimiento cultural en Europa del siglo XIV al XVII",
     "Began in Italy. Revived classical learning. Figures: Leonardo da Vinci, Michelangelo, Raphael, Shakespeare."),
    ("Reformation", "a religious movement that split Western Christianity",
     "un movimiento religioso que dividió el cristianismo occidental",
     "Started in 1517 with Martin Luther's 95 Theses. Resulted in Protestantism. Reshaped European politics."),
    ("fall of the Roman Empire", "the collapse of the Western Roman Empire in 476 AD",
     "el colapso del Imperio Romano Occidental en 476 d.C.",
     "Odoacer deposed Romulus Augustulus. Conventional date for the start of the Middle Ages in Western Europe."),
    ("Age of Exploration", "European overseas exploration from the 15th to 17th centuries",
     "exploración europea de ultramar de los siglos XV al XVII",
     "Portuguese and Spanish voyages. Columbus reached the Americas in 1492. Magellan circumnavigated the globe 1519-1522."),
    ("Moon landing", "NASA's Apollo 11 mission that landed humans on the Moon",
     "la misión Apolo 11 de la NASA que puso humanos en la Luna",
     "July 20, 1969. Neil Armstrong and Buzz Aldrin walked on the surface. First words: 'one small step for man, one giant leap for mankind'."),
    ("discovery of America", "the 1492 arrival of Columbus in the Caribbean",
     "la llegada de Colón al Caribe en 1492",
     "Christopher Columbus, financed by Spain, reached the Bahamas on October 12, 1492. Not the first European contact (Vikings had reached Newfoundland around 1000)."),
    ("Mexican Independence", "Mexico's separation from Spain in 1821",
     "la separación de México de España en 1821",
     "The war began with Miguel Hidalgo's 'Grito de Dolores' on September 16, 1810. Spain recognized Mexican independence in 1821."),
    ("Spanish conquest of the Aztec Empire", "Hernán Cortés's expedition from 1519 to 1521",
     "la expedición de Hernán Cortés de 1519 a 1521",
     "Cortés allied with indigenous peoples opposed to Aztec rule and took Tenochtitlán in August 1521. Ended the Aztec Empire."),
    ("invention of the printing press", "Gutenberg's movable-type printing press around 1440",
     "la imprenta de tipos móviles de Gutenberg alrededor de 1440",
     "Revolutionized the production of books in Europe. Enabled the Reformation and the spread of literacy. Gutenberg Bible printed around 1455."),
    ("Magna Carta", "a 1215 charter that limited the power of the English king",
     "una carta de 1215 que limitó el poder del rey inglés",
     "Signed by King John under pressure from rebellious barons. Established that the king is subject to the law. Influential on later constitutional thought."),
    ("Russian Revolution", "the 1917 revolution that brought the Bolsheviks to power",
     "la revolución de 1917 que llevó a los bolcheviques al poder",
     "Two phases: February Revolution ended the tsar; October Revolution brought Lenin's Bolsheviks. Led to the creation of the Soviet Union."),
    ("Chinese Cultural Revolution", "a sociopolitical movement in China from 1966 to 1976",
     "un movimiento sociopolítico en China de 1966 a 1976",
     "Launched by Mao Zedong. Aimed to purge capitalist and traditional elements. Caused widespread upheaval and suffering."),
    ("end of apartheid", "the end of legal racial segregation in South Africa in 1994",
     "el fin de la segregación racial legal en Sudáfrica en 1994",
     "Apartheid was dismantled by democratic elections in which Nelson Mandela was elected president. He had spent 27 years in prison."),
]


_HISTORICAL_FIGURES = [
    ("Julius Caesar", "a Roman general and statesman",
     "un general y estadista romano",
     "Conquered Gaul, crossed the Rubicon in 49 BC, became dictator. Assassinated on the Ides of March (March 15), 44 BC."),
    ("Alexander the Great", "the king of Macedon who built one of history's largest empires",
     "el rey de Macedonia que construyó uno de los imperios más grandes de la historia",
     "Lived 356-323 BC. Conquered Persia, reached India. Founded Alexandria in Egypt. Died at 32."),
    ("Cleopatra", "the last active pharaoh of Ptolemaic Egypt",
     "la última faraona activa del Egipto ptolemaico",
     "Lived 69-30 BC. Allied with Julius Caesar and later Mark Antony. Her death marked Egypt's absorption into the Roman Empire."),
    ("Isaac Newton", "the English physicist and mathematician",
     "el físico y matemático inglés",
     "1643-1727. Formulated laws of motion and universal gravitation. Co-invented calculus with Leibniz. Principia Mathematica 1687."),
    ("Albert Einstein", "the German-born physicist who developed relativity",
     "el físico nacido en Alemania que desarrolló la relatividad",
     "1879-1955. Special relativity 1905, general relativity 1915. Nobel Prize 1921 for the photoelectric effect (not relativity)."),
    ("Leonardo da Vinci", "an Italian Renaissance polymath",
     "un polímata italiano del Renacimiento",
     "1452-1519. Artist (Mona Lisa, Last Supper) and inventor. Filled notebooks with anatomical studies and engineering designs."),
    ("Napoleon Bonaparte", "French military leader and emperor",
     "líder militar francés y emperador",
     "1769-1821. Rose during the French Revolution, crowned emperor 1804. Conquered much of Europe. Defeated at Waterloo 1815."),
    ("Abraham Lincoln", "the 16th president of the United States",
     "el 16º presidente de Estados Unidos",
     "1809-1865. Led the Union during the Civil War. Issued the Emancipation Proclamation. Assassinated shortly after the war ended."),
    ("Winston Churchill", "British prime minister during World War II",
     "primer ministro británico durante la Segunda Guerra Mundial",
     "1874-1965. Led Britain through WWII. Famous for his speeches and leadership during the Blitz. Won the Nobel Prize in Literature 1953."),
    ("Mahatma Gandhi", "leader of the Indian independence movement",
     "líder del movimiento de independencia de India",
     "1869-1948. Pioneered nonviolent civil disobedience. Led the Salt March 1930. India gained independence in 1947."),
    ("Martin Luther King Jr", "American civil rights leader",
     "líder estadounidense de los derechos civiles",
     "1929-1968. Led the civil rights movement using nonviolent resistance. 'I Have a Dream' speech 1963. Assassinated in Memphis."),
    ("Nelson Mandela", "South African anti-apartheid leader and president",
     "líder antiapartheid y presidente de Sudáfrica",
     "1918-2013. Spent 27 years in prison. Released 1990. Won the Nobel Peace Prize 1993. First democratically elected president of South Africa 1994."),
    ("Marie Curie", "Polish-French physicist and chemist",
     "física y química polaco-francesa",
     "1867-1934. Discovered polonium and radium. First woman to win a Nobel Prize. Only person to win Nobels in two different sciences."),
    ("Galileo Galilei", "Italian astronomer and physicist",
     "astrónomo y físico italiano",
     "1564-1642. Improved the telescope, observed moons of Jupiter, championed heliocentrism. Tried by the Inquisition 1633."),
    ("Christopher Columbus", "the Genoese explorer who crossed the Atlantic for Spain in 1492",
     "el explorador genovés que cruzó el Atlántico para España en 1492",
     "~1451-1506. Made four voyages. Reached the Bahamas, Cuba, Hispaniola, and Central America. Never acknowledged reaching a new continent."),
]


_GEOGRAPHY = [
    ("France", "a country in Western Europe whose capital is Paris",
     "un país de Europa Occidental cuya capital es París",
     "Borders Belgium, Luxembourg, Germany, Switzerland, Italy, Spain. Population about 67 million. Currency: euro. Language: French."),
    ("Germany", "a country in Central Europe whose capital is Berlin",
     "un país de Europa Central cuya capital es Berlín",
     "Population about 83 million. Largest economy in the European Union. Reunified in 1990 after the fall of the Berlin Wall."),
    ("Spain", "a country in Southwestern Europe whose capital is Madrid",
     "un país del suroeste de Europa cuya capital es Madrid",
     "Population about 47 million. Member of the EU and NATO. Official language: Spanish. Currency: euro."),
    ("United States", "a federal republic of 50 states in North America",
     "una república federal de 50 estados en Norteamérica",
     "Capital: Washington D.C. Population about 330 million. Third-largest country by area. Currency: US dollar."),
    ("Brazil", "the largest country in South America",
     "el país más grande de Sudamérica",
     "Capital: Brasília. Population about 215 million. Official language: Portuguese. Home to most of the Amazon rainforest."),
    ("Argentina", "a country in South America whose capital is Buenos Aires",
     "un país de Sudamérica cuya capital es Buenos Aires",
     "Population about 45 million. Official language: Spanish. Second-largest country in South America by area."),
    ("Mexico", "a country in North America whose capital is Mexico City",
     "un país de Norteamérica cuya capital es Ciudad de México",
     "Population about 127 million. Most populous Spanish-speaking country. Home to ancient Maya and Aztec civilizations."),
    ("China", "the most populous country in East Asia",
     "el país más poblado de Asia Oriental",
     "Capital: Beijing. Population about 1.4 billion. Second-largest economy in the world. Official language: Mandarin."),
    ("India", "a country in South Asia with the largest population",
     "un país del sur de Asia con la población más grande",
     "Capital: New Delhi. Population about 1.4 billion. Seventh-largest country by area. Multiple official languages."),
    ("Japan", "an island country in East Asia whose capital is Tokyo",
     "un país insular de Asia Oriental cuya capital es Tokio",
     "Population about 125 million. Fourth-largest economy. Consists of four main islands: Honshu, Hokkaido, Kyushu, Shikoku."),
    ("Russia", "the largest country in the world by land area",
     "el país más grande del mundo por área terrestre",
     "Capital: Moscow. Population about 146 million. Spans eleven time zones. Official language: Russian."),
    ("Egypt", "a country in North Africa whose capital is Cairo",
     "un país del norte de África cuya capital es El Cairo",
     "Population about 110 million. Home to the ancient pyramids of Giza. The Nile River flows through the country."),
    ("Amazon River", "the largest river by discharge volume",
     "el río más grande del mundo por volumen de descarga",
     "In South America. About 6,400 km long. Drains a basin of about 7 million km². Flows through Brazil, Peru, Colombia, and others."),
    ("Nile River", "a major river in northeastern Africa",
     "un gran río del noreste de África",
     "About 6,650 km long, historically considered the longest river in the world. Flows north through Egypt to the Mediterranean."),
    ("Mount Everest", "the highest mountain on Earth above sea level",
     "la montaña más alta de la Tierra sobre el nivel del mar",
     "8,849 meters. In the Himalayas on the border between Nepal and China. First summited by Hillary and Tenzing in 1953."),
    ("Sahara Desert", "the largest hot desert in the world",
     "el desierto cálido más grande del mundo",
     "In North Africa. About 9 million km². Larger than the continental US. Spans many countries from Morocco to Egypt."),
    ("Pacific Ocean", "the largest and deepest ocean on Earth",
     "el océano más grande y profundo de la Tierra",
     "Covers about 63 million square miles. Contains more water than all continents combined. Deepest point: Mariana Trench (~11 km)."),
    ("Atlantic Ocean", "the second-largest ocean",
     "el segundo océano más grande",
     "Separates the Americas from Europe and Africa. Average depth about 3.6 km. Shape approximately S."),
    ("Andes", "the longest mountain range in the world",
     "la cordillera más larga del mundo",
     "Runs along the western edge of South America, about 7,000 km. Highest peak: Aconcagua in Argentina at 6,961 m."),
    ("Himalayas", "the mountain range separating the Indian subcontinent from the Tibetan Plateau",
     "la cordillera que separa el subcontinente indio de la meseta tibetana",
     "Home to 9 of the 10 highest peaks on Earth, including Everest. Extends through India, Nepal, Bhutan, China, and Pakistan."),
]


def facts() -> List[Dict]:
    out = []
    for name, en_short, es_short, detail in _HISTORY_EVENTS:
        out.append({
            "topic": "history",
            "subtopic": "event",
            "q_en": f"What was the {name}?",
            "a_en": f"The {name} was {en_short}. {detail}",
            "q_es": f"¿Qué fue {name}?",
            "a_es": f"{name} fue {es_short}. {detail}",
            "difficulty": "easy",
        })
        out.append({
            "topic": "history",
            "subtopic": "event",
            "q_en": f"Tell me about {name} in a paragraph.",
            "a_en": f"{name}: {en_short}. {detail}",
            "q_es": f"Háblame de {name} en un párrafo.",
            "a_es": f"{name}: {es_short}. {detail}",
            "difficulty": "easy",
        })
    for name, en_short, es_short, detail in _HISTORICAL_FIGURES:
        out.append({
            "topic": "history",
            "subtopic": "figure",
            "q_en": f"Who was {name}?",
            "a_en": f"{name} was {en_short}. {detail}",
            "q_es": f"¿Quién fue {name}?",
            "a_es": f"{name} fue {es_short}. {detail}",
            "difficulty": "easy",
        })
    for name, en_short, es_short, detail in _GEOGRAPHY:
        out.append({
            "topic": "geography",
            "subtopic": "place",
            "q_en": f"What is {name}?",
            "a_en": f"{name} is {en_short}. {detail}",
            "q_es": f"¿Qué es {name}?",
            "a_es": f"{name} es {es_short}. {detail}",
            "difficulty": "easy",
        })
        out.append({
            "topic": "geography",
            "subtopic": "place",
            "q_en": f"Tell me about {name}.",
            "a_en": f"{name}: {en_short}. {detail}",
            "q_es": f"Háblame de {name}.",
            "a_es": f"{name}: {es_short}. {detail}",
            "difficulty": "easy",
        })
    return out
