"""
synth/knowledge/mathematics.py — Hechos reales de matemáticas introductorias.

Cubre: álgebra básica, cálculo de una variable, probabilidad, geometría,
nociones de teoría de números. Todo verificable en un libro de texto
estándar o en Wikipedia.
"""

from __future__ import annotations

from typing import List, Dict


_ALGEBRA = [
    ("linear equation", "an equation of the form ax + b = 0",
     "una ecuación de la forma ax + b = 0",
     "The solution is x = -b/a, provided a != 0. If a = 0 and b = 0, every number is a solution. If a = 0 and b != 0, no solution exists."),
    ("quadratic equation", "an equation of the form ax² + bx + c = 0",
     "una ecuación de la forma ax² + bx + c = 0",
     "The quadratic formula gives x = (-b ± sqrt(b² - 4ac)) / (2a). The discriminant b² - 4ac determines if there are 2 real, 1 double, or 2 complex roots."),
    ("discriminant", "the quantity b² - 4ac for a quadratic ax² + bx + c",
     "la cantidad b² - 4ac en una cuadrática ax² + bx + c",
     "If positive, two distinct real roots. If zero, one repeated real root. If negative, two complex conjugate roots."),
    ("Vieta's formulas", "relations between the coefficients and roots of a polynomial",
     "relaciones entre coeficientes y raíces de un polinomio",
     "For ax² + bx + c = 0: sum of roots = -b/a, product of roots = c/a. Extend to cubics and higher."),
    ("factoring", "writing an expression as a product of simpler factors",
     "escribir una expresión como producto de factores más simples",
     "x² - 5x + 6 = (x - 2)(x - 3). The zero-product property: if AB = 0 then A = 0 or B = 0."),
    ("exponent rules", "rules for manipulating powers",
     "reglas para manipular potencias",
     "a^m · a^n = a^(m+n). (a^m)^n = a^(mn). a^(-n) = 1/a^n. a^0 = 1 for a != 0."),
    ("logarithm", "the inverse function of exponentiation",
     "la función inversa de la exponenciación",
     "log_b(x) = y means b^y = x. Common bases: 10 (common log), e (natural log ln), 2 (binary log)."),
    ("log properties", "rules for manipulating logarithms",
     "reglas para manipular logaritmos",
     "log(xy) = log(x) + log(y). log(x/y) = log(x) - log(y). log(x^n) = n log(x). Change of base: log_b(x) = ln(x)/ln(b)."),
    ("absolute value", "the non-negative value of a number",
     "el valor no negativo de un número",
     "|x| = x if x ≥ 0, -x if x < 0. |x - y| is the distance between x and y on the number line."),
    ("inequality", "a statement comparing expressions with <, >, ≤, or ≥",
     "una declaración que compara expresiones con <, >, ≤ o ≥",
     "When you multiply or divide by a negative number, the inequality flips. |x| < a means -a < x < a."),
    ("system of equations", "two or more equations with shared variables",
     "dos o más ecuaciones con variables compartidas",
     "Solve by substitution, elimination, or matrix methods. A linear system has 0, 1, or infinitely many solutions."),
    ("determinant", "a scalar value computed from a square matrix",
     "un valor escalar calculado de una matriz cuadrada",
     "For 2x2 [[a,b],[c,d]], det = ad - bc. A matrix is invertible if and only if its determinant is nonzero."),
    ("matrix multiplication", "combining two matrices to produce a third",
     "combinar dos matrices para producir una tercera",
     "Row i of A dotted with column j of B gives entry (i,j) of AB. Requires A's columns = B's rows. Not commutative."),
    ("vector", "an ordered list of numbers with magnitude and direction",
     "una lista ordenada de números con magnitud y dirección",
     "In R^n, a vector is an n-tuple. The norm ||v|| = sqrt(v·v). The dot product u·v = sum of u_i v_i."),
    ("dot product", "a scalar produced by multiplying corresponding entries of two vectors and summing",
     "un escalar producido multiplicando entradas correspondientes de dos vectores y sumando",
     "u·v = |u||v|cos(θ) where θ is the angle between them. Zero dot product means the vectors are perpendicular."),
    ("function", "a rule that maps each input to exactly one output",
     "una regla que asigna a cada entrada una salida exacta",
     "The domain is the set of valid inputs. The range is the set of possible outputs."),
    ("composition", "applying one function to the result of another",
     "aplicar una función al resultado de otra",
     "(f ∘ g)(x) = f(g(x)). Order matters: f∘g ≠ g∘f in general."),
    ("inverse function", "a function that undoes another",
     "una función que deshace a otra",
     "f^(-1)(f(x)) = x. A function has an inverse if and only if it is bijective (one-to-one and onto)."),
]


_CALCULUS = [
    ("derivative", "the instantaneous rate of change of a function",
     "la tasa instantánea de cambio de una función",
     "f'(x) = lim_{h→0} (f(x+h) - f(x))/h. It measures slope. If f'(c) > 0 the function is increasing at c."),
    ("power rule", "the derivative of x^n is n·x^(n-1)",
     "la derivada de x^n es n·x^(n-1)",
     "Works for any real exponent n (not just integers). Combined with linearity, it handles all polynomials."),
    ("product rule", "the derivative of fg is f'g + fg'",
     "la derivada de fg es f'g + fg'",
     "If f and g are both differentiable at x, (fg)'(x) = f'(x)g(x) + f(x)g'(x)."),
    ("quotient rule", "the derivative of f/g is (f'g - fg')/g²",
     "la derivada de f/g es (f'g - fg')/g²",
     "Provided g(x) ≠ 0 at the point of interest. Equivalent to the product rule applied to f · g^(-1)."),
    ("chain rule", "the derivative of a composition of functions",
     "la derivada de una composición de funciones",
     "(f(g(x)))' = f'(g(x)) · g'(x). The 'inside and outside' rule. Fundamental for everything beyond polynomials."),
    ("integral", "the signed area under a curve",
     "el área con signo bajo una curva",
     "∫ f(x) dx. The fundamental theorem of calculus links it to antiderivatives: ∫_a^b f'(x) dx = f(b) - f(a)."),
    ("antiderivative", "a function whose derivative is a given function",
     "una función cuya derivada es una función dada",
     "If F'(x) = f(x), then F is an antiderivative of f. Antiderivatives differ by a constant: ∫f = F(x) + C."),
    ("limit", "the value a function approaches as input approaches a point",
     "el valor al que una función se acerca cuando la entrada se acerca a un punto",
     "lim_{x→c} f(x) = L means f(x) can be made arbitrarily close to L by choosing x close enough to c."),
    ("continuity", "a function has no sudden jumps",
     "una función no tiene saltos bruscos",
     "f is continuous at c if lim_{x→c} f(x) = f(c). Informally: you can draw the graph without lifting your pen."),
    ("differentiability implies continuity", "every differentiable function is continuous",
     "toda función diferenciable es continua",
     "The converse is false: |x| is continuous at 0 but not differentiable there."),
    ("Taylor series", "a power series representation of a function around a point",
     "una representación en serie de potencias de una función alrededor de un punto",
     "f(x) = Σ f^(n)(a)(x-a)^n / n!. Useful for approximation. Converges only in a radius of convergence."),
    ("mean value theorem", "there is a point where the tangent slope equals the average slope",
     "existe un punto donde la pendiente tangente iguala la pendiente promedio",
     "For f continuous on [a,b] and differentiable on (a,b), there is c in (a,b) with f'(c) = (f(b)-f(a))/(b-a)."),
    ("fundamental theorem of calculus", "differentiation and integration are inverse operations",
     "diferenciación e integración son operaciones inversas",
     "Part 1: if F(x) = ∫_a^x f(t) dt, then F'(x) = f(x). Part 2: ∫_a^b f(x) dx = F(b) - F(a) where F' = f."),
    ("L'Hôpital's rule", "a technique for limits of 0/0 or ∞/∞",
     "una técnica para límites de forma 0/0 o ∞/∞",
     "If lim f(x) and lim g(x) are both 0 or both infinity, then lim f(x)/g(x) = lim f'(x)/g'(x) if the latter exists."),
    ("partial derivative", "the derivative of a multivariable function in one direction",
     "la derivada de una función multivariable en una dirección",
     "∂f/∂x treats other variables as constants. The gradient ∇f is the vector of all partial derivatives."),
]


_PROBABILITY = [
    ("probability", "a number between 0 and 1 measuring how likely an event is",
     "un número entre 0 y 1 que mide qué tan probable es un evento",
     "P(A) = 0 means A never happens. P(A) = 1 means A always happens. P(not A) = 1 - P(A)."),
    ("independent events", "events whose probabilities multiply",
     "eventos cuyas probabilidades se multiplican",
     "P(A and B) = P(A) · P(B) when A and B are independent. Independence is NOT the same as mutually exclusive."),
    ("mutually exclusive", "events that cannot both happen",
     "eventos que no pueden ocurrir a la vez",
     "P(A and B) = 0. For mutually exclusive events, P(A or B) = P(A) + P(B)."),
    ("conditional probability", "the probability of A given that B has occurred",
     "la probabilidad de A dado que B ha ocurrido",
     "P(A|B) = P(A and B) / P(B), when P(B) > 0. Encodes how B changes the likelihood of A."),
    ("Bayes theorem", "a formula that reverses conditional probabilities",
     "una fórmula que invierte probabilidades condicionales",
     "P(A|B) = P(B|A) · P(A) / P(B). Used in statistics, medical testing, and machine learning."),
    ("expected value", "the long-run average of a random variable",
     "el promedio a largo plazo de una variable aleatoria",
     "E[X] = Σ x · P(X=x). For a fair die, E = 3.5. Also called the mean."),
    ("variance", "the expected squared deviation from the mean",
     "la desviación cuadrada esperada respecto a la media",
     "Var(X) = E[(X - μ)²]. Measures spread. The standard deviation is sqrt(Var)."),
    ("binomial distribution", "the distribution of the number of successes in n independent Bernoulli trials",
     "la distribución del número de éxitos en n ensayos Bernoulli independientes",
     "P(X=k) = C(n,k) p^k (1-p)^(n-k). Mean np, variance np(1-p)."),
    ("normal distribution", "the bell-curve distribution",
     "la distribución en forma de campana",
     "Characterized by mean μ and standard deviation σ. Symmetric. Many real-world phenomena approximately follow it."),
    ("central limit theorem", "the distribution of a sample mean approaches normal",
     "la distribución de la media muestral se acerca a la normal",
     "For independent, identically distributed samples, the sample mean has approximately a normal distribution as n grows."),
    ("uniform distribution", "a distribution where every outcome is equally likely",
     "una distribución donde todos los resultados son igualmente probables",
     "Discrete: each of n outcomes has probability 1/n. Continuous on [a,b]: density 1/(b-a)."),
    ("law of large numbers", "sample averages converge to the expected value",
     "los promedios muestrales convergen al valor esperado",
     "As n grows, the sample mean gets closer to the true mean. Explains why casinos profit long-term."),
    ("Bayesian vs frequentist", "two philosophical interpretations of probability",
     "dos interpretaciones filosóficas de la probabilidad",
     "Frequentist: probability is long-run frequency. Bayesian: probability is a degree of belief updated by evidence."),
]


_GEOMETRY = [
    ("Pythagorean theorem", "in a right triangle, a² + b² = c²",
     "en un triángulo rectángulo, a² + b² = c²",
     "Where a and b are the legs and c is the hypotenuse. Named after Pythagoras of Samos (~570 BC)."),
    ("triangle area", "half base times height",
     "la mitad de la base por la altura",
     "A = (1/2) · b · h. Alternative using sides and angle: A = (1/2) ab sin(C). Heron's formula uses only sides."),
    ("circle area", "pi times radius squared",
     "pi por el radio al cuadrado",
     "A = πr². The circumference is 2πr. π is irrational, approximately 3.14159."),
    ("similar triangles", "triangles with the same angles and proportional sides",
     "triángulos con los mismos ángulos y lados proporcionales",
     "All angles are equal; ratios of corresponding sides are equal. Used in solving indirect measurement problems."),
    ("right angle", "a 90-degree angle",
     "un ángulo de 90 grados",
     "Two lines that meet at a right angle are perpendicular. In a right triangle, the sum of the other two angles is 90°."),
    ("isosceles triangle", "a triangle with at least two equal sides",
     "un triángulo con al menos dos lados iguales",
     "The angles opposite the equal sides are equal. An equilateral triangle is also isosceles."),
    ("equilateral triangle", "a triangle with all sides equal",
     "un triángulo con todos los lados iguales",
     "All interior angles are 60°. All equilateral triangles are similar to each other."),
    ("polygon", "a closed plane figure made of straight line segments",
     "una figura plana cerrada hecha de segmentos rectos",
     "Sum of interior angles of an n-gon is (n-2) · 180°. Regular polygon: all sides and angles equal."),
    ("sphere volume", "four-thirds pi r cubed",
     "cuatro tercios pi r al cubo",
     "V = (4/3)πr³. Surface area = 4πr². Derived by integrating the circle's area over the axis."),
    ("cylinder volume", "pi r squared times height",
     "pi r al cuadrado por altura",
     "V = πr²h. Lateral surface area = 2πrh. Total surface area = 2πr² + 2πrh."),
]


def facts() -> List[Dict]:
    out = []
    for pool, sub in [
        (_ALGEBRA, "algebra"),
        (_CALCULUS, "calculus"),
        (_PROBABILITY, "probability"),
        (_GEOMETRY, "geometry"),
    ]:
        for name, en_short, es_short, detail in pool:
            out.append({
                "topic": "math",
                "subtopic": sub,
                "q_en": f"What is the {name} in mathematics?",
                "a_en": f"The {name} is {en_short}. {detail}",
                "q_es": f"¿Qué es {name} en matemáticas?",
                "a_es": f"{name} es {es_short}. {detail}",
                "difficulty": "medium",
            })
            out.append({
                "topic": "math",
                "subtopic": sub,
                "q_en": f"Explain {name} with context.",
                "a_en": f"In {sub}, {name} is {en_short}. {detail}",
                "q_es": f"Explica {name} con contexto.",
                "a_es": f"En {sub}, {name} es {es_short}. {detail}",
                "difficulty": "medium",
            })
    return out
