"""
synth/knowledge/programming.py — Hechos reales sobre Python, JavaScript, Rust.

Cada entrada es una afirmación factual verificable contra la documentación
oficial del lenguaje. Templating bilingüe en el generador.
"""

from __future__ import annotations

from typing import List, Dict


# ════════════════════════════════════════════════════════════════════════════
# PYTHON — builtins, data types, control flow, stdlib basics
# ════════════════════════════════════════════════════════════════════════════

_PY_BUILTINS = [
    ("len", "returns the number of items in an object",
     "devuelve la cantidad de elementos de un objeto",
     "len() works on strings, lists, tuples, dicts, sets, and any object that implements __len__."),
    ("range", "creates an immutable sequence of numbers",
     "crea una secuencia inmutable de números",
     "range(stop), range(start, stop), or range(start, stop, step). It does not create a list; it is an iterator."),
    ("print", "writes objects to the standard output stream",
     "escribe objetos en la salida estándar",
     "print(*objects, sep=' ', end='\\n', file=sys.stdout, flush=False). Separator defaults to single space."),
    ("input", "reads a line from standard input",
     "lee una línea de entrada estándar",
     "input(prompt) displays the prompt, waits for the user, and returns the entered line as a string."),
    ("type", "returns the type of an object",
     "devuelve el tipo de un objeto",
     "type(obj) returns the class. type(name, bases, dict) can also create a new class dynamically."),
    ("isinstance", "checks if an object is an instance of a class",
     "comprueba si un objeto es instancia de una clase",
     "isinstance(obj, cls) supports a tuple of classes too: isinstance(x, (int, float))."),
    ("int", "creates an integer from a number or string",
     "crea un entero desde un número o una cadena",
     "int(x, base=10). The base can be 2-36. int() alone returns 0."),
    ("float", "creates a floating point number",
     "crea un número de punto flotante",
     "float(x) converts a number or a parseable string. Python floats are 64-bit IEEE 754 doubles."),
    ("str", "creates a string from an object",
     "crea una cadena desde un objeto",
     "str(obj) calls obj.__str__(). Without arguments, str() returns an empty string ''."),
    ("list", "creates a new list",
     "crea una nueva lista",
     "list() returns []. list(iterable) materializes the iterable into a list."),
    ("dict", "creates a new dictionary",
     "crea un nuevo diccionario",
     "dict() returns {}. dict(key=value) works with keyword args. dict(iterable of pairs) also works."),
    ("set", "creates a new set",
     "crea un nuevo conjunto",
     "set() returns an empty set (note: {} is an empty dict, not a set). set(iterable) deduplicates."),
    ("tuple", "creates a new tuple",
     "crea una nueva tupla",
     "tuple() returns (). tuple(iterable) materializes. Tuples are immutable; lists are mutable."),
    ("sorted", "returns a new sorted list from an iterable",
     "devuelve una nueva lista ordenada de un iterable",
     "sorted(iterable, key=None, reverse=False). The key function is applied to each element for comparison."),
    ("reversed", "returns a reverse iterator",
     "devuelve un iterador al revés",
     "reversed(seq) works on any sequence with __reversed__ or __len__ + __getitem__."),
    ("enumerate", "adds an index counter to an iterable",
     "agrega un contador de índice a un iterable",
     "enumerate(iterable, start=0) yields (index, value) pairs. Start lets you shift the counter."),
    ("zip", "aggregates elements from multiple iterables",
     "agrupa elementos de varios iterables",
     "zip(*iterables) stops at the shortest iterable. zip(*iterables, strict=True) raises if they differ."),
    ("map", "applies a function to every item of an iterable",
     "aplica una función a cada elemento de un iterable",
     "map(fn, iterable) returns a map object. It is lazy; use list(map(...)) to materialize."),
    ("filter", "filters items from an iterable by a predicate",
     "filtra elementos de un iterable según un predicado",
     "filter(pred, iterable) keeps items where pred(x) is truthy. filter(None, it) removes falsy items."),
    ("sum", "sums the items of an iterable",
     "suma los elementos de un iterable",
     "sum(iterable, start=0) accumulates. For floats, math.fsum is more accurate due to error compensation."),
    ("min", "returns the smallest item",
     "devuelve el menor elemento",
     "min(iterable) or min(a, b, c). key= for custom comparison. default= for empty iterables."),
    ("max", "returns the largest item",
     "devuelve el mayor elemento",
     "max(iterable) or max(a, b, c). Symmetric to min()."),
    ("abs", "returns the absolute value",
     "devuelve el valor absoluto",
     "abs(x). For complex numbers, returns the magnitude."),
    ("round", "rounds a number to given precision",
     "redondea un número con la precisión dada",
     "round(x, ndigits). With banker's rounding (half to even) to avoid bias."),
    ("divmod", "returns quotient and remainder pair",
     "devuelve el par cociente y resto",
     "divmod(a, b) returns (a // b, a % b) as a tuple."),
    ("open", "opens a file and returns a file object",
     "abre un archivo y devuelve un objeto de archivo",
     "open(path, mode='r', encoding=None). Use a with-block to guarantee close."),
    ("any", "returns True if any element is truthy",
     "devuelve True si algún elemento es truthy",
     "any(iterable) short-circuits on the first truthy value."),
    ("all", "returns True if all elements are truthy",
     "devuelve True si todos los elementos son truthy",
     "all(iterable) short-circuits on the first falsy value. all([]) is True (vacuous truth)."),
    ("repr", "returns the printable representation",
     "devuelve la representación imprimible",
     "repr(obj) calls obj.__repr__(). It should ideally be a Python expression that recreates the object."),
    ("id", "returns the unique identity of an object",
     "devuelve la identidad única de un objeto",
     "id(obj) is the memory address in CPython. Two objects compare equal with 'is' if their ids match."),
    ("hash", "returns a hash value",
     "devuelve un valor de hash",
     "hash(obj) requires obj to be hashable (immutable). Used by sets and dict keys."),
    ("getattr", "returns the value of a named attribute",
     "devuelve el valor de un atributo por nombre",
     "getattr(obj, 'name') raises AttributeError if missing. getattr(obj, 'name', default) returns default."),
    ("setattr", "sets the value of a named attribute",
     "asigna el valor de un atributo por nombre",
     "setattr(obj, 'name', value) is equivalent to obj.name = value."),
    ("hasattr", "returns True if an object has an attribute",
     "devuelve True si un objeto tiene un atributo",
     "hasattr(obj, 'name') is implemented by calling getattr and catching AttributeError."),
    ("callable", "checks if an object appears callable",
     "comprueba si un objeto parece invocable",
     "callable(obj) returns True if obj.__call__ exists. Classes are callable (they produce instances)."),
]

_PY_CONCEPTS = [
    ("list comprehension", "a concise way to build a list from an iterable",
     "una forma concisa de construir una lista desde un iterable",
     "[expression for item in iterable if condition]. It is more Pythonic and usually faster than a for-loop with .append()."),
    ("dict comprehension", "a concise way to build a dict from an iterable",
     "una forma concisa de construir un dict desde un iterable",
     "{key_expr: value_expr for item in iterable if condition}. Same idea as list comprehensions."),
    ("generator expression", "a lazy iterator defined with generator syntax",
     "un iterador perezoso definido con sintaxis de generador",
     "(x*2 for x in range(10)). Generators produce items on demand, not all at once. Memory efficient."),
    ("decorator", "a function that modifies another function",
     "una función que modifica otra función",
     "@decorator above a def is equivalent to func = decorator(func). Common for @staticmethod, @property, @functools.cache."),
    ("context manager", "a protocol for resource management with with-statement",
     "un protocolo para gestión de recursos con la declaración with",
     "Implements __enter__ and __exit__. The with-block guarantees __exit__ is called even on exception."),
    ("with statement", "the statement that uses a context manager",
     "la declaración que usa un context manager",
     "with open('file') as f: guarantees f.close() runs even if an exception is raised inside the block."),
    ("generator function", "a function that yields values lazily",
     "una función que produce valores de forma perezosa",
     "Using yield instead of return. Each call resumes where it left off. Generators are iterators."),
    ("lambda", "an anonymous function expression",
     "una expresión de función anónima",
     "lambda args: expression. Used for short callbacks. Cannot contain statements, only a single expression."),
    ("f-string", "a string that embeds expressions inside braces",
     "una cadena que incorpora expresiones entre llaves",
     "f'Hello, {name}!'. Introduced in Python 3.6. Supports format spec: f'{x:.2f}'."),
    ("tuple unpacking", "assigning multiple variables from an iterable",
     "asignar varias variables desde un iterable",
     "a, b, c = (1, 2, 3). With * you can capture the rest: a, *rest = [1,2,3,4]."),
    ("slicing", "selecting a sub-sequence",
     "seleccionar una subsecuencia",
     "s[start:stop:step]. Negative indices count from the end. s[::-1] reverses the sequence."),
    ("truthy", "a value that evaluates True in a boolean context",
     "un valor que evalúa True en contexto booleano",
     "Empty collections, 0, '', None are falsy. Everything else is truthy by default. __bool__ can override."),
    ("duck typing", "a style where behavior matters more than class",
     "un estilo donde el comportamiento importa más que la clase",
     "If it walks like a duck and quacks like a duck, it is a duck. Type checks are often skipped in Python."),
    ("GIL", "the Global Interpreter Lock in CPython",
     "el bloqueo global del intérprete en CPython",
     "Only one thread executes Python bytecode at a time, even on multicore. I/O releases the GIL; CPU work does not."),
    ("asyncio", "Python's standard library for async concurrency",
     "la biblioteca estándar de Python para concurrencia asíncrona",
     "async def defines a coroutine. await pauses it. The event loop schedules coroutines cooperatively."),
    ("dataclass", "a decorator that auto-generates __init__ and __repr__",
     "un decorador que genera __init__ y __repr__ automáticamente",
     "from dataclasses import dataclass. @dataclass class Point: x: int; y: int. Great for plain data holders."),
    ("type hint", "an optional annotation describing the type of a variable",
     "una anotación opcional que describe el tipo de una variable",
     "def f(x: int) -> str: ... Hints are not enforced at runtime; tools like mypy check them statically."),
    ("virtual environment", "an isolated Python environment for a project",
     "un entorno Python aislado para un proyecto",
     "python -m venv .venv creates one. Activate it so pip installs into the project, not globally."),
    ("pip", "the standard package installer for Python",
     "el instalador de paquetes estándar de Python",
     "pip install package. pip freeze > requirements.txt saves the current environment."),
    ("PEP 8", "the official Python style guide",
     "la guía de estilo oficial de Python",
     "4-space indent, 79-char line limit, snake_case for functions/variables, CamelCase for classes."),
    ("__init__", "the constructor method of a class",
     "el método constructor de una clase",
     "Called when an instance is created. Takes self as the first argument plus any args from the caller."),
    ("self", "the explicit reference to the instance in methods",
     "la referencia explícita a la instancia en los métodos",
     "Python does not hide the receiver. self is a convention, not a keyword; any name works but self is standard."),
    ("mutable vs immutable", "whether an object can change after creation",
     "si un objeto puede cambiar después de ser creado",
     "int, float, str, tuple, frozenset, bytes are immutable. list, dict, set, bytearray are mutable."),
    ("shallow copy", "a copy that shares nested objects",
     "una copia que comparte objetos anidados",
     "list.copy() or list(x) or x[:]. Changes to nested mutable items are visible in both copies."),
    ("deep copy", "a copy that recursively duplicates nested objects",
     "una copia que duplica recursivamente los objetos anidados",
     "copy.deepcopy(x). Independent from the original at every level. Slower than shallow copy."),
    ("pickle", "binary serialization for Python objects",
     "serialización binaria para objetos Python",
     "pickle.dumps(obj) serializes; pickle.loads(data) deserializes. Never unpickle untrusted data."),
    ("JSON", "text serialization format",
     "formato de serialización de texto",
     "json.dumps/loads. Can serialize dicts, lists, strings, numbers, booleans, None. Not tuples or sets directly."),
    ("regex", "regular expressions, pattern matching on strings",
     "expresiones regulares, búsqueda de patrones en cadenas",
     "import re. re.search for first match; re.findall for all; re.sub for replace. Use r'' strings."),
    ("walrus operator", "assignment expression := added in Python 3.8",
     "operador morsa := añadido en Python 3.8",
     "if (n := len(lst)) > 10: allows using the value in the same expression where it is computed."),
    ("match statement", "structural pattern matching added in Python 3.10",
     "declaración match, pattern matching estructural añadido en 3.10",
     "match value: case pattern: ... case _: ... Similar to switch but much more powerful (destructuring)."),
]


def _py_facts() -> List[Dict]:
    out = []
    for name, en_short, es_short, detail in _PY_BUILTINS:
        out.append({
            "topic": "programming",
            "subtopic": "python_builtin",
            "q_en": f"What does the Python {name} function do?",
            "a_en": f"{name} {en_short}. {detail}",
            "q_es": f"¿Qué hace la función {name} de Python?",
            "a_es": f"{name} {es_short}. {detail}",
            "difficulty": "easy",
        })
        out.append({
            "topic": "programming",
            "subtopic": "python_builtin",
            "q_en": f"In Python, how does {name} behave with edge cases?",
            "a_en": f"The Python built-in {name} {en_short}. {detail}",
            "q_es": f"En Python, ¿cómo se comporta {name} en casos borde?",
            "a_es": f"La función {name} {es_short}. {detail}",
            "difficulty": "medium",
        })
    for name, en_short, es_short, detail in _PY_CONCEPTS:
        out.append({
            "topic": "programming",
            "subtopic": "python_concept",
            "q_en": f"What is a {name} in Python?",
            "a_en": f"A {name} is {en_short}. {detail}",
            "q_es": f"¿Qué es un {name} en Python?",
            "a_es": f"Un {name} es {es_short}. {detail}",
            "difficulty": "medium",
        })
        out.append({
            "topic": "programming",
            "subtopic": "python_concept",
            "q_en": f"Explain the Python {name} with an example.",
            "a_en": f"In Python, a {name} {en_short}. {detail}",
            "q_es": f"Explica el {name} de Python con un ejemplo.",
            "a_es": f"En Python, un {name} {es_short}. {detail}",
            "difficulty": "medium",
        })
    return out


# ════════════════════════════════════════════════════════════════════════════
# JAVASCRIPT
# ════════════════════════════════════════════════════════════════════════════

_JS_CONCEPTS = [
    ("var vs let vs const", "three ways to declare a variable with different scoping rules",
     "tres formas de declarar una variable con distintas reglas de alcance",
     "var is function-scoped and hoisted. let and const are block-scoped. const cannot be reassigned but objects can still mutate."),
    ("arrow function", "a concise function expression syntax",
     "una sintaxis concisa para expresiones de función",
     "(x) => x * 2. Arrow functions do not have their own 'this'; they inherit from the enclosing scope."),
    ("Promise", "an object representing an async operation's eventual result",
     "un objeto que representa el resultado eventual de una operación asíncrona",
     "new Promise((resolve, reject) => ...). States: pending, fulfilled, rejected. Chain with .then() and .catch()."),
    ("async/await", "syntactic sugar for Promises",
     "azúcar sintáctico para Promises",
     "async function f() returns a Promise. await x pauses execution until x resolves. Only usable inside async functions."),
    ("closure", "a function that captures variables from its enclosing scope",
     "una función que captura variables de su ámbito circundante",
     "Closures remember their lexical environment even after the outer function has returned."),
    ("this", "the reference to the execution context",
     "la referencia al contexto de ejecución",
     "In regular functions, 'this' depends on how the function is called. In arrow functions, it is lexically inherited."),
    ("hoisting", "moving declarations to the top of the scope at parse time",
     "mover declaraciones al principio del ámbito al parsear",
     "var declarations are hoisted (but not initializations). let/const are hoisted into a temporal dead zone."),
    ("prototype", "the object from which another object inherits properties",
     "el objeto desde el que otro objeto hereda propiedades",
     "Every JS object has a prototype. obj.__proto__ or Object.getPrototypeOf(obj). The basis of JS inheritance."),
    ("destructuring", "extracting values from arrays or objects into variables",
     "extraer valores de arrays u objetos en variables",
     "const {a, b} = obj or const [x, y] = arr. Also works in function parameters."),
    ("spread operator", "expanding an iterable into individual elements",
     "expandir un iterable en elementos individuales",
     "...array or ...object. Used in function calls, array literals, and object literals."),
    ("Object.assign", "copies properties from sources to a target object",
     "copia propiedades de fuentes a un objeto destino",
     "Object.assign(target, ...sources). Shallow copy. Returns the modified target."),
    ("Array.map", "creates a new array with results of calling a function on every element",
     "crea un nuevo array con el resultado de aplicar una función a cada elemento",
     "arr.map(fn) returns a new array the same length as arr. Does not mutate the original."),
    ("Array.filter", "creates a new array with elements that pass a test",
     "crea un nuevo array con elementos que pasan un test",
     "arr.filter(pred) returns a new array of items where pred(item) is truthy."),
    ("Array.reduce", "reduces an array to a single value",
     "reduce un array a un solo valor",
     "arr.reduce((acc, item) => ..., initialValue). The initial value is important for empty arrays."),
    ("null vs undefined", "two distinct falsy values with different meanings",
     "dos valores falsy distintos con significados diferentes",
     "undefined means not assigned. null means intentionally empty. typeof null === 'object' (a famous bug)."),
    ("== vs ===", "loose vs strict equality",
     "igualdad laxa vs estricta",
     "== does type coercion. === compares both type and value without coercion. Prefer === always."),
    ("event loop", "the runtime model that handles async callbacks",
     "el modelo de ejecución que maneja los callbacks asíncronos",
     "JS is single-threaded. The loop processes the callback queue after the call stack is empty."),
    ("setTimeout", "schedules a callback to run after a delay",
     "programa un callback para ejecutarse después de un retraso",
     "setTimeout(fn, ms). The delay is a minimum, not exact — the callback may run later if the loop is busy."),
    ("JSON.parse", "parses a JSON string into a JS object",
     "convierte una cadena JSON en un objeto JS",
     "JSON.parse(text). Throws SyntaxError on invalid JSON. Cannot handle functions or undefined."),
    ("JSON.stringify", "converts a JS value to a JSON string",
     "convierte un valor JS en una cadena JSON",
     "JSON.stringify(value, replacer, space). The space parameter pretty-prints the output."),
    ("fetch API", "modern browser API for HTTP requests",
     "API moderna del navegador para peticiones HTTP",
     "fetch(url).then(r => r.json()). Returns a Promise. Does not reject on 4xx/5xx; check response.ok."),
    ("DOM", "Document Object Model, the browser's page representation",
     "Document Object Model, la representación del navegador de la página",
     "Document represents the HTML. querySelector and querySelectorAll find elements. addEventListener attaches handlers."),
    ("module", "a file with its own scope that exports bindings",
     "un archivo con su propio scope que exporta bindings",
     "export and import. ES modules are static (unlike CommonJS require). Browsers support them natively."),
    ("strict mode", "a restricted JS dialect that catches more errors",
     "un dialecto JS restringido que detecta más errores",
     "'use strict' at the top of a file or function. Disables silent errors, forbids undeclared variables."),
    ("TypeScript", "a typed superset of JavaScript",
     "un superconjunto tipado de JavaScript",
     "Adds optional static types. Compiles down to plain JS. Catches errors at compile time. Published by Microsoft."),
]


def _js_facts() -> List[Dict]:
    out = []
    for name, en_short, es_short, detail in _JS_CONCEPTS:
        out.append({
            "topic": "programming",
            "subtopic": "javascript",
            "q_en": f"What is {name} in JavaScript?",
            "a_en": f"In JavaScript, {name} is {en_short}. {detail}",
            "q_es": f"¿Qué es {name} en JavaScript?",
            "a_es": f"En JavaScript, {name} es {es_short}. {detail}",
            "difficulty": "medium",
        })
        out.append({
            "topic": "programming",
            "subtopic": "javascript",
            "q_en": f"Explain {name} in JS with a short example.",
            "a_en": f"{name} in JavaScript is {en_short}. {detail}",
            "q_es": f"Explica {name} en JS con un ejemplo corto.",
            "a_es": f"{name} en JavaScript es {es_short}. {detail}",
            "difficulty": "medium",
        })
    return out


# ════════════════════════════════════════════════════════════════════════════
# RUST
# ════════════════════════════════════════════════════════════════════════════

_RUST_CONCEPTS = [
    ("ownership", "Rust's system for managing memory without a garbage collector",
     "el sistema de Rust para gestionar memoria sin recolector de basura",
     "Every value has a unique owner. When the owner goes out of scope, the value is dropped. No double-frees."),
    ("borrowing", "taking a reference to a value without taking ownership",
     "tomar una referencia a un valor sin tomar la posesión",
     "&T is an immutable borrow; &mut T is mutable. You can have many immutables XOR one mutable at a time."),
    ("lifetime", "a compile-time label that tracks how long a reference is valid",
     "una etiqueta en tiempo de compilación que rastrea cuánto vive una referencia",
     "Lifetimes prevent use-after-free. 'a is a lifetime parameter. Most are inferred by the compiler."),
    ("trait", "a shared interface that types can implement",
     "una interfaz compartida que los tipos pueden implementar",
     "Similar to interfaces in Java or type classes in Haskell. impl Trait for Type adds the implementation."),
    ("enum", "a type that can be one of several variants",
     "un tipo que puede ser una de varias variantes",
     "enum Option<T> { Some(T), None }. Each variant can carry data. Exhaustive matching is enforced."),
    ("Option", "the type for values that may or may not exist",
     "el tipo para valores que pueden existir o no",
     "Option<T> is Some(T) or None. Replaces null. The compiler forces you to handle the None case."),
    ("Result", "the type for operations that may fail",
     "el tipo para operaciones que pueden fallar",
     "Result<T, E> is Ok(T) or Err(E). Replaces exceptions. The ? operator propagates errors concisely."),
    ("cargo", "Rust's package manager and build tool",
     "el gestor de paquetes y herramienta de build de Rust",
     "cargo new, cargo build, cargo test, cargo run. Dependencies are declared in Cargo.toml."),
    ("match expression", "pattern matching that is exhaustive by default",
     "pattern matching que es exhaustivo por defecto",
     "match x { pattern => result, _ => fallback }. The compiler errors if you miss a case."),
    ("Vec", "a growable heap-allocated array",
     "un array en heap que puede crecer",
     "Vec<T>. Push with .push(), access with [] (panics) or .get() (returns Option)."),
    ("String vs &str", "owned vs borrowed string types",
     "tipo string propio vs prestado",
     "String is owned, growable, UTF-8. &str is a view. Literals are &'static str."),
    ("async/await in Rust", "cooperative concurrency with a runtime",
     "concurrencia cooperativa con un runtime",
     "async fn returns a Future. .await polls it. You need a runtime like tokio to actually execute futures."),
    ("unsafe", "a block that lets you bypass some compiler checks",
     "un bloque que permite saltarse algunas comprobaciones del compilador",
     "unsafe { ... }. Required for raw pointers, FFI, and certain optimizations. Use sparingly."),
    ("derive macro", "a procedural macro that auto-implements traits",
     "un macro procedural que implementa traits automáticamente",
     "#[derive(Debug, Clone, PartialEq)] generates the boilerplate. Common traits support derive."),
    ("Cargo.toml", "the manifest file for a Rust project",
     "el archivo manifiesto para un proyecto de Rust",
     "Describes metadata, dependencies, and build configuration. The lockfile Cargo.lock records exact versions."),
]


def _rust_facts() -> List[Dict]:
    out = []
    for name, en_short, es_short, detail in _RUST_CONCEPTS:
        out.append({
            "topic": "programming",
            "subtopic": "rust",
            "q_en": f"What is {name} in Rust?",
            "a_en": f"In Rust, {name} is {en_short}. {detail}",
            "q_es": f"¿Qué es {name} en Rust?",
            "a_es": f"En Rust, {name} es {es_short}. {detail}",
            "difficulty": "medium",
        })
    return out


# ════════════════════════════════════════════════════════════════════════════
# Public API
# ════════════════════════════════════════════════════════════════════════════

def facts() -> List[Dict]:
    out = []
    out.extend(_py_facts())
    out.extend(_js_facts())
    out.extend(_rust_facts())
    return out
