"""
synth/knowledge/science.py — Hechos reales de ciencia introductoria.

Física, química, biología nivel entrada. Todo verificable en un libro
introductorio de ciencia o en Wikipedia.
"""

from __future__ import annotations

from typing import List, Dict


_PHYSICS = [
    ("Newton's first law", "an object in motion stays in motion unless acted upon by a force",
     "un objeto en movimiento permanece en movimiento a menos que una fuerza actúe sobre él",
     "Also called the law of inertia. An object at rest stays at rest unless pushed or pulled."),
    ("Newton's second law", "force equals mass times acceleration",
     "la fuerza es igual a la masa por la aceleración",
     "F = ma. The heavier an object or the greater its acceleration, the more force is needed."),
    ("Newton's third law", "for every action there is an equal and opposite reaction",
     "para cada acción hay una reacción igual y opuesta",
     "Forces come in pairs. When you push on a wall, the wall pushes back on you with equal force."),
    ("gravity", "the force of attraction between masses",
     "la fuerza de atracción entre masas",
     "On Earth's surface, g ≈ 9.81 m/s². Newton's law of universal gravitation: F = G m₁m₂/r²."),
    ("conservation of energy", "energy cannot be created or destroyed, only transformed",
     "la energía no se puede crear ni destruir, solo transformar",
     "Kinetic energy becomes potential, heat, sound, etc. Total energy of a closed system is constant."),
    ("kinetic energy", "the energy of motion",
     "la energía del movimiento",
     "KE = (1/2) m v². Doubles if speed increases by sqrt(2). Quadruples if speed doubles."),
    ("potential energy", "stored energy due to position or configuration",
     "energía almacenada debido a posición o configuración",
     "Gravitational PE near Earth: U = mgh. Spring PE: (1/2) k x² where k is the stiffness."),
    ("momentum", "the product of mass and velocity",
     "el producto de masa y velocidad",
     "p = mv. Conserved in a closed system. Collisions exchange momentum between objects."),
    ("speed of light", "the universal speed limit in a vacuum",
     "la velocidad límite universal en el vacío",
     "c ≈ 299,792,458 m/s. Nothing with mass can travel at c. Light in matter travels slower."),
    ("wavelength", "the distance between consecutive peaks of a wave",
     "la distancia entre picos consecutivos de una onda",
     "λ. Frequency f and wavelength are related by c = fλ for light, v = fλ for other waves."),
    ("frequency", "the number of wave cycles per second",
     "el número de ciclos de onda por segundo",
     "Measured in Hertz (Hz). Human hearing covers about 20 Hz to 20,000 Hz."),
    ("voltage", "the electric potential difference between two points",
     "la diferencia de potencial eléctrico entre dos puntos",
     "Measured in volts (V). Ohm's law: V = IR, where I is current and R is resistance."),
    ("current", "the flow of electric charge",
     "el flujo de carga eléctrica",
     "Measured in amperes (A). One ampere is one coulomb of charge per second."),
    ("electromagnetic spectrum", "the range of all electromagnetic radiation",
     "el rango de toda la radiación electromagnética",
     "From low-frequency radio waves to gamma rays. Visible light is a tiny band (roughly 380-750 nm)."),
    ("thermodynamics first law", "energy of an isolated system is constant",
     "la energía de un sistema aislado es constante",
     "ΔU = Q - W, where Q is heat added and W is work done by the system."),
    ("thermodynamics second law", "entropy of an isolated system never decreases",
     "la entropía de un sistema aislado nunca decrece",
     "Heat flows from hot to cold. No cyclic machine can convert heat to work with 100% efficiency."),
    ("absolute zero", "the coldest possible temperature",
     "la temperatura más baja posible",
     "0 K = -273.15 °C = -459.67 °F. At absolute zero, molecular motion reaches its minimum (not zero due to quantum effects)."),
    ("relativity", "Einstein's theory that space and time are linked",
     "la teoría de Einstein que enlaza espacio y tiempo",
     "Special relativity (1905): laws of physics are the same in all inertial frames. General relativity (1915): gravity is curvature of spacetime."),
]


_CHEMISTRY = [
    ("atom", "the smallest unit of an element that retains its properties",
     "la unidad más pequeña de un elemento que retiene sus propiedades",
     "Composed of a nucleus (protons + neutrons) surrounded by electrons in orbitals."),
    ("proton", "a positively charged particle in the nucleus",
     "una partícula con carga positiva en el núcleo",
     "The number of protons (atomic number Z) defines the element. Hydrogen has 1, helium 2, carbon 6."),
    ("neutron", "a neutrally charged particle in the nucleus",
     "una partícula sin carga en el núcleo",
     "Protons + neutrons = mass number (A). Isotopes of an element have different numbers of neutrons."),
    ("electron", "a negatively charged particle orbiting the nucleus",
     "una partícula con carga negativa que orbita el núcleo",
     "Mass is about 1/1836 of a proton. Electrons in the outer shell (valence) drive chemical bonding."),
    ("periodic table", "a tabular arrangement of the chemical elements",
     "una disposición tabular de los elementos químicos",
     "Organized by atomic number, electron configuration, and recurring properties. Grouped into periods and groups."),
    ("chemical bond", "an attraction between atoms that holds them together",
     "una atracción entre átomos que los mantiene unidos",
     "Types: ionic (transfer of electrons), covalent (sharing of electrons), metallic (delocalized electrons)."),
    ("ionic bond", "a bond formed by electron transfer between atoms",
     "un enlace formado por transferencia de electrones entre átomos",
     "Typically between a metal (loses electrons) and a nonmetal (gains electrons). Example: Na+ + Cl- = NaCl."),
    ("covalent bond", "a bond formed by sharing electrons between atoms",
     "un enlace formado por compartir electrones entre átomos",
     "Typical of nonmetal-nonmetal bonds. H2O has two covalent bonds. Covalent bonds can be single, double, or triple."),
    ("water", "a compound of two hydrogen atoms and one oxygen atom",
     "un compuesto de dos átomos de hidrógeno y uno de oxígeno",
     "Formula H2O. Bent geometry, polar molecule. Essential solvent for life. Melting 0°C, boiling 100°C."),
    ("pH", "a measure of acidity or alkalinity of a solution",
     "una medida de la acidez o alcalinidad de una solución",
     "Scale from 0 to 14. 7 is neutral (pure water). Below 7 acidic, above 7 basic. pH = -log[H+]."),
    ("molecule", "a group of atoms bonded together",
     "un grupo de átomos unidos por enlace",
     "Simplest unit of a compound. Can be diatomic (O2, N2) or polyatomic (H2O, CO2, CH4)."),
    ("mole", "a unit for amount of substance",
     "una unidad de cantidad de sustancia",
     "One mole = Avogadro's number ≈ 6.022 × 10^23 particles. Used to relate mass and molecular count."),
    ("Avogadro number", "the number of particles in one mole",
     "el número de partículas en un mol",
     "N_A ≈ 6.022 × 10^23. Named after Amedeo Avogadro. The defining constant since 2019 SI redefinition."),
    ("acid", "a substance that donates protons or accepts electron pairs",
     "una sustancia que dona protones o acepta pares de electrones",
     "Common acids: HCl, H2SO4, CH3COOH (vinegar). Strong acids fully dissociate in water."),
    ("base", "a substance that accepts protons or donates electron pairs",
     "una sustancia que acepta protones o dona pares de electrones",
     "Common bases: NaOH, KOH, NH3. Bases feel slippery and turn litmus paper blue."),
    ("oxidation", "loss of electrons during a chemical reaction",
     "pérdida de electrones en una reacción química",
     "Remember OIL RIG: Oxidation Is Loss, Reduction Is Gain. The two processes always happen together in redox."),
    ("combustion", "a rapid reaction between a fuel and an oxidant",
     "una reacción rápida entre un combustible y un oxidante",
     "Typically with oxygen, producing heat and light. Complete combustion of hydrocarbons yields CO2 and H2O."),
]


_BIOLOGY = [
    ("cell", "the basic unit of life",
     "la unidad básica de la vida",
     "All living organisms are made of cells. Prokaryotes (bacteria) have no nucleus. Eukaryotes (plants, animals, fungi) do."),
    ("DNA", "deoxyribonucleic acid, the molecule that encodes genetic information",
     "ácido desoxirribonucleico, la molécula que codifica información genética",
     "Double helix of nucleotides with bases A, T, C, G. Replicated during cell division."),
    ("RNA", "ribonucleic acid, a single-stranded molecule used in protein synthesis",
     "ácido ribonucleico, una molécula de una sola hebra usada en síntesis de proteínas",
     "Messenger RNA carries a copy of a gene from DNA to the ribosome. Transfer RNA brings amino acids."),
    ("gene", "a segment of DNA that codes for a protein or function",
     "un segmento de ADN que codifica una proteína o función",
     "Genes are arranged on chromosomes. Humans have about 20,000 protein-coding genes."),
    ("chromosome", "a long DNA molecule with genes",
     "una molécula larga de ADN con genes",
     "Humans have 46 chromosomes in 23 pairs. One pair determines sex (XX or XY)."),
    ("protein", "a large biomolecule made of amino acids",
     "una biomolécula grande hecha de aminoácidos",
     "20 standard amino acids. Proteins fold into specific shapes that determine their function (enzymes, transport, etc.)."),
    ("enzyme", "a protein that catalyzes a biochemical reaction",
     "una proteína que cataliza una reacción bioquímica",
     "Enzymes speed up reactions without being consumed. Highly specific: each enzyme acts on particular substrates."),
    ("mitochondria", "the organelle that produces ATP",
     "el orgánulo que produce ATP",
     "Often called the powerhouse of the cell. Has its own DNA, inherited from the mother in animals."),
    ("photosynthesis", "the process plants use to convert sunlight into chemical energy",
     "el proceso que usan las plantas para convertir luz solar en energía química",
     "CO2 + H2O + light → C6H12O6 + O2. Occurs in chloroplasts. Produces the oxygen we breathe."),
    ("respiration", "the process of converting glucose and oxygen into energy",
     "el proceso de convertir glucosa y oxígeno en energía",
     "C6H12O6 + 6 O2 → 6 CO2 + 6 H2O + ATP. Happens in mitochondria in eukaryotes."),
    ("mitosis", "cell division that produces two identical daughter cells",
     "división celular que produce dos células hijas idénticas",
     "Phases: prophase, metaphase, anaphase, telophase. Used for growth and repair in multicellular organisms."),
    ("meiosis", "cell division that produces four non-identical gametes",
     "división celular que produce cuatro gametos no idénticos",
     "Halves the chromosome number. Creates genetic variation through crossover and independent assortment."),
    ("evolution", "change in allele frequencies in a population over generations",
     "cambio en frecuencias de alelos en una población a lo largo de generaciones",
     "Driven by natural selection, mutation, drift, and gene flow. First described by Darwin and Wallace."),
    ("natural selection", "differential survival and reproduction based on traits",
     "supervivencia y reproducción diferencial basada en rasgos",
     "Individuals with favorable traits leave more descendants. Over many generations, populations adapt."),
    ("DNA replication", "the process of copying a DNA molecule",
     "el proceso de copiar una molécula de ADN",
     "Semiconservative: each new double helix has one old strand and one new one. Catalyzed by DNA polymerase."),
    ("ecosystem", "a community of organisms and their physical environment",
     "una comunidad de organismos y su entorno físico",
     "Producers (plants), consumers (animals), and decomposers. Energy flows one way; matter cycles."),
    ("food chain", "a linear sequence of who eats whom",
     "una secuencia lineal de quién come a quién",
     "Grass → zebra → lion. Each level is a trophic level. Only about 10% of energy transfers between levels."),
]


def facts() -> List[Dict]:
    out = []
    for pool, sub in [
        (_PHYSICS, "physics"),
        (_CHEMISTRY, "chemistry"),
        (_BIOLOGY, "biology"),
    ]:
        for name, en_short, es_short, detail in pool:
            out.append({
                "topic": "science",
                "subtopic": sub,
                "q_en": f"What is {name}?",
                "a_en": f"{name[0].upper() + name[1:]} is {en_short}. {detail}",
                "q_es": f"¿Qué es {name}?",
                "a_es": f"{name[0].upper() + name[1:]} es {es_short}. {detail}",
                "difficulty": "easy",
            })
            out.append({
                "topic": "science",
                "subtopic": sub,
                "q_en": f"Give me a short explanation of {name}.",
                "a_en": f"In {sub}, {name} refers to {en_short}. {detail}",
                "q_es": f"Dame una breve explicación de {name}.",
                "a_es": f"En {sub}, {name} se refiere a {es_short}. {detail}",
                "difficulty": "easy",
            })
    return out
