"""
synth/knowledge/technology.py — Hechos reales de tecnología e internet.

Conceptos reales de redes, bases de datos, APIs, protocolos, sistemas
operativos. Verificables en RFCs, MDN, documentación oficial.
"""

from __future__ import annotations

from typing import List, Dict


_INTERNET_NETWORKING = [
    ("HTTP", "the Hypertext Transfer Protocol used for web communication",
     "el Protocolo de Transferencia de Hipertexto usado para comunicación web",
     "Stateless request-response protocol. Runs on top of TCP (usually port 80). HTTPS adds TLS encryption on port 443."),
    ("HTTPS", "HTTP over TLS, providing encrypted communication",
     "HTTP sobre TLS, proporcionando comunicación cifrada",
     "Encrypts the request and response so intermediaries cannot read them. Verifies the server with a certificate."),
    ("TCP", "the Transmission Control Protocol for reliable connections",
     "el Protocolo de Control de Transmisión para conexiones fiables",
     "Handles ordering, retransmission, and flow control. Connection-oriented (three-way handshake). Most web traffic uses TCP."),
    ("UDP", "the User Datagram Protocol for lightweight connectionless communication",
     "el Protocolo de Datagramas de Usuario para comunicación ligera sin conexión",
     "No ordering or retransmission. Lower overhead. Used for video, voice, DNS, and game traffic where speed beats reliability."),
    ("IP address", "a numerical label identifying a device on a network",
     "una etiqueta numérica que identifica un dispositivo en una red",
     "IPv4 uses 32 bits (about 4.3 billion addresses). IPv6 uses 128 bits. Example IPv4: 192.168.1.1."),
    ("DNS", "the Domain Name System that maps names to IP addresses",
     "el Sistema de Nombres de Dominio que mapea nombres a direcciones IP",
     "When you type example.com, DNS resolves it to an IP. Hierarchical system: root servers, TLDs, authoritative servers."),
    ("URL", "a Uniform Resource Locator identifying a resource on the web",
     "un Localizador Uniforme de Recursos que identifica un recurso en la web",
     "Format: scheme://host:port/path?query#fragment. Example: https://example.com/docs?page=1."),
    ("REST API", "an architectural style for web services using HTTP verbs",
     "un estilo arquitectónico para servicios web usando verbos HTTP",
     "Uses GET, POST, PUT, DELETE, PATCH. Resources identified by URLs. Stateless between requests. Commonly uses JSON."),
    ("WebSocket", "a protocol for full-duplex communication over a single TCP connection",
     "un protocolo para comunicación full-duplex sobre una sola conexión TCP",
     "Starts as HTTP and upgrades. Allows servers to push messages to clients without polling. Used for chat, live data, games."),
    ("JSON", "JavaScript Object Notation, a data interchange format",
     "Notación de Objetos de JavaScript, un formato de intercambio de datos",
     "Text-based, language-agnostic. Supports objects, arrays, strings, numbers, booleans, null. Dominant API format."),
    ("XML", "Extensible Markup Language, a verbose data format",
     "Lenguaje de Marcado Extensible, un formato de datos verboso",
     "Uses tags like HTML. Supports namespaces, schemas, validation. Largely replaced by JSON for APIs but still used in SOAP and some enterprise contexts."),
    ("TLS", "Transport Layer Security, the protocol that encrypts HTTPS",
     "Seguridad de la Capa de Transporte, el protocolo que cifra HTTPS",
     "Successor of SSL. Provides encryption, authentication, and integrity. Current version TLS 1.3 (2018). Uses certificates signed by CAs."),
    ("port", "a number identifying a specific application on a device",
     "un número que identifica una aplicación específica en un dispositivo",
     "16-bit number (0-65535). HTTP on 80, HTTPS on 443, SSH on 22, DNS on 53. Ephemeral ports used by clients."),
    ("packet", "a formatted unit of data carried by a network",
     "una unidad de datos formateada transportada por una red",
     "Contains headers (addresses, metadata) and payload. Networks route packets hop by hop. TCP reassembles them into a stream."),
    ("router", "a device that forwards packets between networks",
     "un dispositivo que reenvía paquetes entre redes",
     "Operates at the network layer (L3). Uses routing tables to decide the next hop. Home routers also do NAT and DHCP."),
    ("NAT", "Network Address Translation that maps private IPs to a public IP",
     "Traducción de Direcciones de Red que mapea IPs privadas a una IP pública",
     "Allows many devices behind a router to share one public IP. Typical home network uses 192.168.x.x internally."),
    ("DHCP", "Dynamic Host Configuration Protocol that assigns IPs automatically",
     "Protocolo de Configuración Dinámica de Hosts que asigna IPs automáticamente",
     "When a device joins a network, it asks DHCP for an IP, subnet mask, gateway, and DNS. Runs on UDP."),
    ("CDN", "Content Delivery Network that caches content near users",
     "Red de Distribución de Contenido que cachea contenido cerca de los usuarios",
     "Servers distributed globally. Reduces latency and bandwidth costs. Examples: Cloudflare, Akamai, AWS CloudFront."),
    ("GET vs POST", "two HTTP methods with different semantics",
     "dos métodos HTTP con semántica diferente",
     "GET is safe and idempotent; parameters in URL. POST is for changing server state; body can carry arbitrary data. GET is cacheable."),
    ("status code", "a three-digit code in HTTP responses",
     "un código de tres dígitos en respuestas HTTP",
     "1xx informational, 2xx success, 3xx redirect, 4xx client error, 5xx server error. 200 OK, 404 Not Found, 500 Internal Server Error."),
]


_DATABASES = [
    ("SQL", "Structured Query Language for relational databases",
     "Lenguaje Estructurado de Consultas para bases de datos relacionales",
     "Standard since 1986. SELECT, INSERT, UPDATE, DELETE, JOIN. Declarative: you say what you want, not how to get it."),
    ("relational database", "a database organized as tables with rows and columns",
     "una base de datos organizada como tablas con filas y columnas",
     "Based on relational algebra. Tables have schemas. Rows are records. Relationships use foreign keys."),
    ("primary key", "a column or set of columns that uniquely identifies each row",
     "una columna o conjunto de columnas que identifica únicamente cada fila",
     "Must be unique and not null. Often auto-incremented integer or UUID. Tables usually have exactly one primary key."),
    ("foreign key", "a column that references the primary key of another table",
     "una columna que referencia la clave primaria de otra tabla",
     "Enforces referential integrity. A row cannot reference a nonexistent row in the other table. Enables JOINs."),
    ("JOIN", "an operation that combines rows from two or more tables",
     "una operación que combina filas de dos o más tablas",
     "INNER JOIN: only matching rows. LEFT JOIN: all from left, matching from right. FULL OUTER JOIN: both sides."),
    ("index", "a data structure that speeds up lookups at the cost of storage and write speed",
     "una estructura de datos que acelera búsquedas a costa de espacio y velocidad de escritura",
     "Usually implemented as a B-tree. Queries with WHERE or ORDER BY on indexed columns are faster. Writes require index updates."),
    ("NoSQL", "a family of non-relational databases",
     "una familia de bases de datos no relacionales",
     "Include document stores (MongoDB), key-value (Redis), column-family (Cassandra), graph (Neo4j). Trade SQL for scale or flexibility."),
    ("ACID", "four properties of reliable transactions",
     "cuatro propiedades de transacciones fiables",
     "Atomicity (all or nothing), Consistency (valid states only), Isolation (no interference), Durability (persists on commit)."),
    ("transaction", "a sequence of operations treated as a single unit of work",
     "una secuencia de operaciones tratada como una sola unidad de trabajo",
     "BEGIN, operations, COMMIT (or ROLLBACK). Either all operations succeed or none do. Required for money transfers and many other use cases."),
    ("normalization", "organizing tables to reduce redundancy",
     "organizar tablas para reducir la redundancia",
     "Normal forms (1NF, 2NF, 3NF, BCNF) eliminate duplication. Helps avoid update anomalies. Denormalization trades storage for read speed."),
    ("SQL injection", "a vulnerability where user input is executed as SQL",
     "una vulnerabilidad donde la entrada del usuario se ejecuta como SQL",
     "Attack: \"'; DROP TABLE users; --\". Prevention: parameterized queries / prepared statements, never concatenate user input."),
    ("CRUD", "the four basic operations: Create, Read, Update, Delete",
     "las cuatro operaciones básicas: Crear, Leer, Actualizar, Borrar",
     "Map to SQL INSERT, SELECT, UPDATE, DELETE. Also to HTTP POST, GET, PUT/PATCH, DELETE in REST APIs."),
    ("PostgreSQL", "an open-source relational database known for correctness",
     "una base de datos relacional de código abierto conocida por su corrección",
     "Supports advanced features: JSONB, full-text search, GIS, window functions. BSD-style license. Widely used in production."),
    ("MySQL", "another widely used open-source relational database",
     "otra base de datos relacional de código abierto muy usada",
     "Owned by Oracle. GPL license. Known for ease of use and performance on simple workloads. Forked as MariaDB."),
    ("SQLite", "an embedded SQL database that runs as a library",
     "una base de datos SQL embebida que corre como biblioteca",
     "No server process. Stores the whole database in a single file. Ubiquitous: Android apps, browsers, operating systems use it."),
    ("MongoDB", "a document-oriented NoSQL database",
     "una base de datos NoSQL orientada a documentos",
     "Stores JSON-like documents with flexible schemas. Uses BSON internally. Popular for rapid development."),
    ("Redis", "an in-memory key-value store",
     "un almacén clave-valor en memoria",
     "Extremely fast. Supports data structures: strings, lists, sets, hashes, sorted sets. Used for caching, queues, pub/sub."),
]


_OS_BASICS = [
    ("process", "an instance of a program in execution",
     "una instancia de un programa en ejecución",
     "Has its own memory space, file handles, and state. The OS scheduler decides which processes run when."),
    ("thread", "a unit of execution within a process",
     "una unidad de ejecución dentro de un proceso",
     "Threads share memory with other threads in the same process. Cheaper to create than processes. Need synchronization to avoid race conditions."),
    ("file system", "the OS mechanism for organizing files on storage",
     "el mecanismo del SO para organizar archivos en almacenamiento",
     "Common types: ext4 (Linux), NTFS (Windows), APFS (macOS). Provides hierarchy, permissions, metadata."),
    ("kernel", "the core of an operating system",
     "el núcleo de un sistema operativo",
     "Manages CPU, memory, devices, and system calls. Runs in privileged mode. Linux kernel, Windows NT kernel, XNU (macOS)."),
    ("shell", "a program that provides a command-line interface to the OS",
     "un programa que proporciona una interfaz de línea de comandos al SO",
     "bash, zsh, fish on Unix. PowerShell and cmd on Windows. Interprets commands, runs programs, composes them with pipes."),
    ("pipe", "a Unix mechanism to connect the output of one command to the input of another",
     "un mecanismo Unix para conectar la salida de un comando con la entrada de otro",
     "grep error log.txt | wc -l. The pipe operator | sends stdout of the left to stdin of the right."),
    ("virtual memory", "the OS technique of giving each process its own address space",
     "la técnica del SO de dar a cada proceso su propio espacio de direcciones",
     "Maps virtual addresses to physical RAM through page tables. Allows using more memory than is physically available (via swap)."),
    ("git", "a distributed version control system",
     "un sistema de control de versiones distribuido",
     "Created by Linus Torvalds in 2005. Every clone is a full repository. Branches are cheap. The standard for source control."),
    ("Docker", "a platform for containerization",
     "una plataforma para contenerización",
     "Packages an application with its dependencies into a container. Containers share the host kernel but have isolated filesystems and processes."),
    ("Linux", "an open-source Unix-like operating system kernel",
     "un kernel de sistema operativo tipo Unix de código abierto",
     "Created by Linus Torvalds in 1991. Used with GNU tools in distributions: Debian, Ubuntu, Fedora, Arch. Powers most servers and Android."),
    ("API", "an Application Programming Interface",
     "una Interfaz de Programación de Aplicaciones",
     "A set of functions and conventions that one program exposes for other programs to use. Web APIs use HTTP; language APIs use function calls."),
    ("library", "a reusable collection of code",
     "una colección reutilizable de código",
     "Imported and called by applications. Examples: the Python standard library, libc, NumPy. Contrast with frameworks which invert control."),
    ("framework", "a software skeleton that calls your code",
     "un esqueleto de software que llama a tu código",
     "You fill in specific behaviors; the framework runs the main loop. Examples: Django, React, Rails. Inversion of control vs libraries."),
    ("compiler", "a program that translates source code into machine code",
     "un programa que traduce código fuente en código máquina",
     "gcc, clang, rustc, javac. Produces an executable or bytecode. Usually does optimization passes."),
    ("interpreter", "a program that executes source code directly",
     "un programa que ejecuta código fuente directamente",
     "Python, Ruby, many scripting languages. Slower than compiled but no build step. Modern interpreters often use JIT compilation."),
    ("garbage collection", "automatic memory management",
     "gestión automática de memoria",
     "The runtime reclaims memory that is no longer reachable. Common in Java, Python, C#, Go. Rust uses ownership instead."),
    ("TCP handshake", "the three-step process TCP uses to establish a connection",
     "el proceso de tres pasos que usa TCP para establecer una conexión",
     "Client sends SYN. Server responds SYN-ACK. Client replies ACK. Connection established. Closing uses a four-step teardown."),
    ("OSI model", "a conceptual model of seven network layers",
     "un modelo conceptual de siete capas de red",
     "Physical, Data Link, Network, Transport, Session, Presentation, Application. Mostly educational; real networks often use the TCP/IP four-layer model."),
    ("operating system", "software that manages hardware and provides services to applications",
     "software que gestiona hardware y proporciona servicios a aplicaciones",
     "Examples: Windows, macOS, Linux, Android, iOS. Provides process management, memory management, file system, and user interfaces."),
    ("ASCII", "a character encoding using 7 bits",
     "una codificación de caracteres que usa 7 bits",
     "128 characters including uppercase and lowercase English letters, digits, punctuation, control codes. Superset: UTF-8."),
    ("UTF-8", "the dominant character encoding of the web",
     "la codificación de caracteres dominante en la web",
     "Variable-length encoding of Unicode. ASCII is a subset. Can represent every character in every human language."),
    ("URL encoding", "the percent-encoding of characters in URLs",
     "la codificación por porcentaje de caracteres en URLs",
     "Replaces unsafe characters with %XX hex. Space is %20, # is %23. Required for query parameters with special characters."),
    ("cookie", "a small piece of data stored by the browser on behalf of a website",
     "un pequeño dato almacenado por el navegador para un sitio web",
     "Sent back with each request. Used for sessions, tracking. Attributes: Secure, HttpOnly, SameSite."),
    ("cache", "a temporary store that speeds up subsequent accesses",
     "un almacén temporal que acelera accesos subsecuentes",
     "HTTP cache, CPU cache, database query cache. Tradeoff: speed vs staleness. Invalidation is famously one of the hardest problems."),
    ("load balancer", "a component that distributes traffic across multiple servers",
     "un componente que distribuye tráfico entre varios servidores",
     "Operates at L4 (TCP) or L7 (HTTP). Strategies: round-robin, least connections, IP hash. Improves scalability and availability."),
    ("firewall", "a system that filters network traffic based on rules",
     "un sistema que filtra tráfico de red según reglas",
     "Allows or blocks packets by source, destination, port, or protocol. Can be host-based (iptables) or network-based (hardware appliance)."),
]


def facts() -> List[Dict]:
    out = []
    for pool, sub in [
        (_INTERNET_NETWORKING, "networking"),
        (_DATABASES, "database"),
        (_OS_BASICS, "os"),
    ]:
        for name, en_short, es_short, detail in pool:
            out.append({
                "topic": "technology",
                "subtopic": sub,
                "q_en": f"What is {name}?",
                "a_en": f"{name} is {en_short}. {detail}",
                "q_es": f"¿Qué es {name}?",
                "a_es": f"{name} es {es_short}. {detail}",
                "difficulty": "medium",
            })
            out.append({
                "topic": "technology",
                "subtopic": sub,
                "q_en": f"Explain {name} for a developer.",
                "a_en": f"{name}: {en_short}. {detail}",
                "q_es": f"Explica {name} para un desarrollador.",
                "a_es": f"{name}: {es_short}. {detail}",
                "difficulty": "medium",
            })
    return out
